### ISSUE TITLE
Iphone X

### ISSUE THREAD

**Issue by MattiaConfalonieri** [souzainf3/RNNotificationView#3]
Is possible add Iphone X support?

**Comment by eytanschulman** [comment]
+1

**Comment by BharathiT2S** [comment]
In iPhone X the notification looks like chopped. can we fix that?

**Comment by djaygit** [comment]
+1

**Comment by souzainf3** [comment]
I'm started an updating to fix layout in iPhone x. Coming soon...

**Comment by souzainf3** [comment]
Fixed in [3.0.1](https://github.com/souzainf3/RNNotificationView/releases/tag/3.0.1) version
